### ISSUE TITLE
Hello ligi

### ISSUE THREAD

**Issue by mxito3** [ligi/Riddim#1]
Hello ligi, because I want to do a staking pool in goerli testnest, I need 100,000 goerli ETH. I want to ask you if you can sell it to me, I will offer $3000 for 100,000. Thank you very much. 
Sorry to disturb you here, because i can't dm u at twitter.
My Telegram:@gucici30

**Comment by ligi** [comment]
I do not have these amounts of goerli-eth and if I would have them I would use them for FaucETH ;-)
Sorry & GL

**Comment by mxito3** [comment]
> I do not have these amounts of goerli-eth and if I would have them I would use them for FaucETH ;-) Sorry & GL

Thank you ligi, Do u have friends who can sell to me?

**Comment by q9f** [comment]
No https://twitter.com/q9fmz/status/1505939597615935492
